// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqi1ZsG1XdQ7nRXVU0xbzEuwaqD7SkBik',
    appId: '1:18491747418:web:6e0edb0f24103ca0a73c63',
    messagingSenderId: '18491747418',
    projectId: 'karmacoin-83d45',
    authDomain: 'karmacoin-83d45.firebaseapp.com',
    storageBucket: 'karmacoin-83d45.appspot.com',
    measurementId: 'G-BY4MSSGR0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFRIu5QhlWHvxvDlU-CrhF5ZqMJd-9D3E',
    appId: '1:18491747418:android:f616de2070a4e67ca73c63',
    messagingSenderId: '18491747418',
    projectId: 'karmacoin-83d45',
    storageBucket: 'karmacoin-83d45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSdm_ICSvy4AdKYTc398zDvPpWr0_LaSo',
    appId: '1:18491747418:ios:d3620bee1a4166dea73c63',
    messagingSenderId: '18491747418',
    projectId: 'karmacoin-83d45',
    storageBucket: 'karmacoin-83d45.appspot.com',
    androidClientId:
        '18491747418-6c7u5ufmclidi8krdkkhb95slm0pr7uq.apps.googleusercontent.com',
    iosClientId:
        '18491747418-n6131nol2snlk8cm6qjmn16k5abns6br.apps.googleusercontent.com',
    iosBundleId: 'in.karmaco.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSdm_ICSvy4AdKYTc398zDvPpWr0_LaSo',
    appId: '1:18491747418:ios:53c65ab065dfac77a73c63',
    messagingSenderId: '18491747418',
    projectId: 'karmacoin-83d45',
    storageBucket: 'karmacoin-83d45.appspot.com',
    androidClientId:
        '18491747418-6c7u5ufmclidi8krdkkhb95slm0pr7uq.apps.googleusercontent.com',
    iosClientId:
        '18491747418-5tt7c8g8cfbui123hdr4okq56d9eil6d.apps.googleusercontent.com',
    iosBundleId: 'in.karmaco.app.RunnerTests',
  );
}
