# This is a basic workflow to help you get started with Actions

name: Build and deploy web app to github pages
on:
  push:
    branches:
      - deploy-web

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: 'Clear flutter cache'
        run: flutter clean   
      - name: 'Run flutter pub get'
        run: flutter pub get
      #    - name: 'Run Test(s)'
      #      run: flutter test
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: clear flutter cache
        run: flutter clean
      - name: 'Build Web App'
        run: flutter build web --release
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
